### ISSUE TITLE
Viewer crashes before showing rows

### ISSUE THREAD

**Issue by fgbaezp** [aloneguid/parquet-viewer-uwp#10]
I'm trying to open Parquet Viewer (installed from Microsoft Store) with a file sized 7,27KB. The viewer shows for a few seconds the columns of the file but the content is never displayed. I can see the content of the file using the command line parq utility and it only has two rows and 35 columns.

**Comment by aloneguid** [comment]
Can you attach the file please, happy to look at this.

**Comment by RinsibleElk** [comment]
Don't know if this will be useful (for you or others seenig the issue), but I was seeing this behaviour also - for some reason I needed to reset the app to get it to work:
https://mspoweruser.com/mspu-solution-windows-10-apps-not-opening-or-hangs-on-launch/
and now it works fine.

**Comment by blaxoid** [comment]
Having the same issue when opening a 24MB parquet file. I'm unable to share it as full of sensitive data. The UI populates the schema but hangs when trying to open the file & eventually crashes

**Comment by hetal-metro** [comment]
I am facing the same issue. it works sometimes and it crash sometime within few second.
for even small parquet file
