### ISSUE TITLE
Windows Apache Parquet Viewer crash in seconds

### ISSUE THREAD

**Issue by esarabia3** [aloneguid/parquet-viewer-uwp#12]
Parquet viewer start without problems but, after reading a parquet files, crash in seconds

**Comment by aloneguid** [comment]
closing, no info provided

**Comment by esarabia3** [comment]
It crashes with this file:

[part-00000-c2a75d7b-ecda-4c35-ac35-2cdad7632ab0-c000.snappy.parquet.zip](https://github.com/aloneguid/parquet-viewer-uwp/files/2254817/part-00000-c2a75d7b-ecda-4c35-ac35-2cdad7632ab0-c000.snappy.parquet.zip)
