### ISSUE TITLE
S3 protocal should read

### ISSUE THREAD

**Issue by mujahed85** [aloneguid/parquet-viewer-uwp#13]
Kindly consideration this repository should work with S3 protocal and online file viewer.

https://s3.console.aws.amazon.com/s3/buckets/amazon-reviews-pds/parquet/?region=us-east-1&tab=overview

like this should display contents of files.

**Comment by aloneguid** [comment]
I already have something in the works for this feature, not only limited to S3 but many more services. It's not going to be ready for public for another month or two though.

**Comment by mujahed85** [comment]
Thank you very much if you need any help in that let me know i will try my level best, i have good knowledge on s3,lambda and hdfs(Hadoop Distribution File System).

**Comment by aloneguid** [comment]
Thanks @mujahed85 we'll be most probably using polycloud storage library https://github.com/aloneguid/storage for this.
