### ISSUE TITLE
Ugly wrap

### ISSUE THREAD

**Issue by aloneguid** [aloneguid/parquet-viewer-uwp#3]
![image](https://user-images.githubusercontent.com/3155189/32013904-74b82fce-b9b4-11e7-98d5-ee7097377b09.png)

probably hard to guess when to wrap, however in this case date columns should never!

**Comment by marrrcin** [comment]
It will be nice if you could add some setting / button in menu, like "auto size columns", which will expand width of columns to match their content length if it's longer than their label.
