### ISSUE TITLE
Problems with wide data

### ISSUE THREAD

**Issue by marrrcin** [aloneguid/parquet-viewer-uwp#4]
I have parquet file with around 20k rows and 2k columns, application is not able to load it (at least under 2 minutes). File size is only 4MB. Data contains sparse matrix.

**Comment by aloneguid** [comment]
Hey thanks, is there any chance I could get that file to test? Generally there is no issues with files much bigger than that so must be a bug

**Comment by marrrcin** [comment]
Sure, I've generated similar file for you:
[bigfile.zip](https://github.com/aloneguid/parquet-viewer-uwp/files/1479213/bigfile.zip)

Code to generate this file (Python 3.6):
```
import pandas as pd
import random
from uuid import uuid4

cols = 900
columns = ["title"] + list(map(lambda col: f"column_#_{col}", range(0, cols)))
data = []
for i in range(0, 20000):
    data.append([f"title {uuid4()}"] + list(map(lambda _: random.random() if random.random()>0.99 else 0.0, range(0, cols))))

df = pd.DataFrame(data=data, columns=columns)
df.to_parquet("bigfile.parquet")
```

**Comment by aloneguid** [comment]
Thanks for this, looks like grid control is struggling with a lot of columns.

**Comment by aloneguid** [comment]
2k columns are not viewable from user's perspective so I won't be implementing this. Feel free to reopen and work on it though.
