### ISSUE TITLE
Cannot find primitive by type INT32 and annotation 24

### ISSUE THREAD

**Issue by gdoron** [aloneguid/parquet-viewer-uwp#5]
Hi,

I'm writing a parquet file using pyarrow, nothing too fancy or complicated and getting this error message:

`data` is an array of dictionaries.
```python
df = pd.DataFrame(data)
table = pa.Table.from_pandas(df)
directory = '..\data\parquet\{0}'.format(date)
pathlib.Path(directory).mkdir(parents=True, exist_ok=True)
pq.write_table(table, '{0}\{1}'.format(directory, file_name), compression='gzip')
```
![image](https://user-images.githubusercontent.com/6141009/32901900-b3170e42-caf9-11e7-88fc-d5a8b4be14bb.png)

Can you tell what's wrong from it?
Or do I need to upload the file itself? (it will require some sanitazations first from sensitive data)

**Comment by aloneguid** [comment]
hey @gdoron  can I get a sample file please?

**Comment by aloneguid** [comment]
I guess not ;)

**Comment by gdoron** [comment]
Hi, sorry for not replying, very rude of me, extremely busy times at work and all...

Anyway, I'm not sure if it's because my schema changed or a new version was released (both happened) but I manage to open the files now!

Greatly appreciating your work man, and again I'm sorry for not following up on time.
