### ISSUE TITLE
Scrolling with the Mouse is not working

### ISSUE THREAD

**Issue by gbrueckl** [aloneguid/parquet-viewer-uwp#7]
Scrolling with the Mouse is not working

**Comment by aloneguid** [comment]
I just checked and it does!
![2018-01-24_15-19-05](https://user-images.githubusercontent.com/3155189/35340049-0f1409ec-011a-11e8-9daa-fe8b8ab88578.gif)

**Comment by gbrueckl** [comment]
I just checked again and indeed, it is working now. Don't know what was wrong when I tested it initially - sorry
I can confirm it its working as expected
